name: keyboard_detection
description: This plugin gives you an easy way to detect if the keyboard is visible or not.
version: 0.2.0
homepage: https://github.com/vursin/keyboard_detection

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
