name: keyboard_detection
description: This plugin gives you an easy way to detect the keyboard visibility.
version: 0.7.0
homepage: https://github.com/lamnhan066/keyboard_detection

screenshots:
  - description: "Introduction"
    path: assets/Intro.webp

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
