name: keyboard_detection
description: This plugin gives you an easy way to detect if the keyboard is visible or not using bottom view insets.
version: 0.5.0
homepage: https://github.com/vursin/keyboard_detection

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
