name: keyboard_detection
description: A Flutter plugin to easily detect keyboard visibility using the bottom view inset.
version: 0.7.3
homepage: https://github.com/lamnhan066/keyboard_detection
topics:
  - keyboard
  - detection
  - visibility

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

