name: keyboard_detection
description: This plugin gives you an easy way to detect the keyboard visibility.
version: 0.6.0
homepage: https://github.com/vnniz/keyboard_detection

screenshots:
  - description: "Introduction"
    path: assets/Intro.webp

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
